Tenta_Version6/Models/Loan.cs
namespace Tenta_Version6.Models
{
    public class Loan
    {
        public int Id { get; set; }
    }
}

Tenta_Version6/Controllers/LoanController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Tenta_Version6.Models;

namespace Tenta_Version6.Controllers
{
    public class LoansController : Controller
    {
        private readonly ApplicationContext Context;

        public LoansController(ApplicationContext _context)
        {
            Context = _context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult UserLoan()
        {


            return View();
        }


        public IActionResult LoanBook()
        {
            List<Genre> AuthorsProductsGenres = Context.Genres.Include(x => x.Books).ThenInclude(x => x.Authors).ToList();

            return View(AuthorsProductsGenres);
        }

        [HttpPost]
        public IActionResult LoanBookPage(int Id)
        {
            Book CurrentBook = Context.Books.
                Where(x => x.Id == Id).FirstOrDefault();
            return View(CurrentBook);
        }
    }
}

Tenta_Version6/Views/Loans/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Tenta_Version6/Views/Loans/LoanBook.cshtml
@model List<Genre>
<!--<link rel="stylesheet" href="app.css" type="text/css" />-->


<h1>Books Available to Loan</h1>
@foreach (Genre Item in Model)
{

    <h2>Genre:@Item.GenreName</h2>
    <hr>
    <div class="row">

        @foreach (var book in Item.Books)
        {
            <div class="col-md-3 mb-3">
                <div class="card">
                    <h4 class="card-header" name="Title"> @Html.DisplayFor(modelItem => book.Title)</h4>
                    <div class="card-body">
                        <p class="card" name="Description">Description: @Html.DisplayFor(modelItem => book.Description)</p>
                        <p class="card" name="Quantity">Quantity: @Html.DisplayFor(modelItem => book.Quantity)</p>
                        <p class="card" name="ISBN">ISBN: @Html.DisplayFor(modelItem => book.ISBN)</p>
                        @foreach (var author in book.Authors)
                        {
                            <p class="card">Author: @Html.DisplayFor(modelItem => author.AuthorName)</p>
                        }
                    </div>
                    <div class="card-footer">
                        <form asp-controller="Loans" asp-action="LoanBookPage" method="POST">
                            <input hidden name="Id" value="@book.Id">
                            <td><input type="submit" class="btn btn-secondary" value="Loan Book" /></td>
                        </form>
                    </div>
                </div>
            </div>

        }
    </div>
}

Tenta_Version6/Views/Loans/LoanBookPage.cshtml
@model List<User>
<h1>Choose User Wich is Loaning Book</h1>
@{

    foreach (User Item in Model)
    {

        <div class="col-md-3 mb-3">
            <div class="card">
                <h4 class="card-header" name="UserName">UserName: @Html.DisplayFor(modelItem => Item.Name)</h4>
                <div class="card-body">
                    <p class="card" name="UserAddress">Address: @Html.DisplayFor(modelItem => Item.Address)</p>
                    <p class="card" name="UserPhoneNumber">Phone Number: @Html.DisplayFor(modelItem => Item.PhoneNumber)</p>
                </div>
                <div class="card-footer">
                    <form asp-controller="Loans" asp-action="UserLoan" method="POST">
                        <input hidden name="removeUserId" value="@Item.Id">
                        <td><input type="submit" class="btn btn-danger" value="Loan" /></td>
                    </form>
                </div>
            </div>
        </div>

    }
}

Tenta_Version6/Views/Loans/UserLoan.cshtml
@model List<User>

<h1>Wich User Is Loaning The Book</h1>
@{

    foreach (User Item in Model)
    {

        <div class="col-md-3 mb-3">
                <div class="card">
                    <h4 class="card-header" name="UserName">UserName: @Html.DisplayFor(modelItem => Item.Name)</h4>
                    <div class="card-body">
                        <p class="card" name="UserAddress">Address: @Html.DisplayFor(modelItem => Item.Address)</p>
                        <p class="card" name="UserPhoneNumber">Phone Number: @Html.DisplayFor(modelItem => Item.PhoneNumber)</p>
                    </div>
                    <div class="card-footer">
                    <form asp-controller="Loans" asp-action="UserLoan" method="POST">
                        <input hidden name="UserLoanId" value="@Item.Id">
                        <td><input type="submit" class="btn btn-success" value="Loan Book"/></td>
                    </form>
                </div>
                </div>
        </div>

    }
}